/**
 * Email delivery for the daily brief.
 *
 * Credentials are read from .env and never originate here. For Gmail, SMTP_PASS
 * must be an App Password generated by the account owner (Google account →
 * Security → App passwords, which requires 2-Step Verification); the ordinary
 * account password will be rejected by Google.
 */
import nodemailer from 'nodemailer';
import { config } from '../config';
import type { DailyBrief } from '../services/briefService';

export interface EmailResult {
  sent: boolean;
  reason?: string;
}

/** HTML-escape. Brief text is generated, but holding names come from the issuer file. */
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Built from the DailyBrief structure rather than by parsing the markdown, so
 * the email cannot drift from the data the brief was computed on.
 *
 * Deliberately inline-styled and table-free: mail clients strip <style> blocks,
 * and this needs to stay readable in Gmail on a phone.
 */
function renderHtml(b: DailyBrief): string {
  const li = (items: Array<{ line: string; newsLines: string[] }>): string =>
    items.length === 0
      ? '<li style="color:#666">none</li>'
      : items
          .map(
            (m) =>
              `<li style="margin:0 0 8px">${esc(m.line)}` +
              (m.newsLines.length
                ? `<div style="color:#555;font-size:13px;margin-top:2px">` +
                  m.newsLines.map(esc).join('<br>') +
                  `</div>`
                : '') +
              `</li>`,
          )
          .join('');

  const section = (title: string, inner: string): string =>
    `<h3 style="font:600 15px system-ui;margin:22px 0 8px">${esc(title)}</h3>${inner}`;

  const banner = b.synthetic
    ? `<p style="background:#fee;border:1px solid #c00;color:#900;padding:10px;
         border-radius:6px;font:600 14px system-ui">
         SYNTHETIC FIXTURE DATA — this does not describe the real fund.</p>`
    : '';

  return `<div style="font:14px/1.55 system-ui,-apple-system,sans-serif;color:#111;
    max-width:640px;margin:0 auto;padding:8px">
  ${banner}
  <h2 style="font:700 20px system-ui;margin:0 0 4px">BAI daily brief — ${esc(b.date)}</h2>
  <p style="font:600 17px system-ui;margin:12px 0">${esc(b.headline)}</p>
  <p style="margin:8px 0">${esc(b.fundLine)}</p>
  ${b.vsMarketLine ? `<p style="margin:8px 0">${esc(b.vsMarketLine)}</p>` : ''}
  ${b.themeLine ? `<p style="margin:8px 0">${esc(b.themeLine)}</p>` : ''}
  ${section('What pulled it up', `<ul style="margin:0;padding-left:20px">${li(b.movers.up)}</ul>`)}
  ${section('What dragged it down', `<ul style="margin:0;padding-left:20px">${li(b.movers.down)}</ul>`)}
  ${
    b.managerLines.length
      ? section(
          'Manager activity',
          `<ul style="margin:0;padding-left:20px">${b.managerLines
            .map((l) => `<li style="margin:0 0 6px">${esc(l)}</li>`)
            .join('')}</ul>`,
        )
      : ''
  }
  ${
    b.caveats.length
      ? section(
          'Data caveats',
          `<ul style="margin:0;padding-left:20px;color:#555;font-size:13px">${b.caveats
            .map((c) => `<li style="margin:0 0 6px">${esc(c)}</li>`)
            .join('')}</ul>`,
        )
      : ''
  }
  <hr style="border:0;border-top:1px solid #ddd;margin:24px 0 10px">
  <p style="color:#777;font-size:12px;margin:0">
    Generated ${esc(b.generatedAt)} · <a href="http://localhost:8787">open the dashboard</a><br>
    Educational only — not investment advice. Past performance does not predict future results.
  </p>
</div>`;
}

/**
 * Send the brief. Returns rather than throws: the brief file is already on disk
 * by the time this runs, and a mail outage must not fail the job or mark the
 * day's brief as missing.
 */
export async function emailBrief(
  b: DailyBrief,
  markdown: string,
): Promise<EmailResult> {
  const { to, host, port, user, pass } = config.delivery.email;
  if (!to || !user || !pass) {
    return {
      sent: false,
      reason:
        'email not configured — set BRIEF_EMAIL_TO, SMTP_USER and SMTP_PASS in .env',
    };
  }

  try {
    const transport = nodemailer.createTransport({
      host,
      port,
      secure: port === 465, // 465 = implicit TLS; 587 upgrades via STARTTLS
      auth: { user, pass },
    });

    await transport.sendMail({
      from: `BAI Tracker <${user}>`,
      to,
      subject: `BAI ${b.date} — ${b.headline.replace(/\*\*/g, '')}`,
      text: markdown, // plain-text alternative for clients that refuse HTML
      html: renderHtml(b),
    });
    return { sent: true };
  } catch (err) {
    // Redact the credential in case a transport error echoes the config back.
    const raw = err instanceof Error ? err.message : String(err);
    return { sent: false, reason: raw.split(pass).join('[redacted]') };
  }
}
